export const languageContent = {
  English: {
    payments: "Payments",
    down_payment: "Down Payment",
    paying_tax_investing_somewhere:
      "Paying the tax and investing somewhere else",
    paying_tax_at_period_end: "Paying tax at period end",
    tax: "Tax",
    pay_installment_cost: "Pay installment cost",
    pay_indexing_cost: "Pay indexing cost",
    gradual_payment: "Gradual Payment",
    pay: "Pay",
    target_irr: "Target IRR",
    real_estate_irr: "Real Estate IRR",
    irr: "IRR",
    irr_no_reconstruction: "IRR in case there is no reconstruction",
    net_yearly_return_on_rent: "Net yearly return on rent",
    yearly_return_from_rent: "Yearly return from rent",
    return_cashflow: "Expected Return (Cash Flow)",
    total_roi: "Total roi",
    return_appreciation: "Expected Return (Appreciation)",
    bad: "Bad",
    current_scenario: "Current Scenario",
    good: "Good",
    original: "Original",
    armageddon: "Armageddon",
    armageddon_scenario: "Armageddon Scenario",
    margin_ceiling: "Margin Ceiling",
    real_estate_holding_period: "Real estate holding period (years)",
    grace_period: "Grace Period",
    configure: "Configure",
    role: "Role",
    description: "Description",
    expected_cashflow: "Expected Cashflow",
    cashflow: "Cashflow",
    multi_generational: "Multi-generational",
    strategic_planning: "Strategic planning",
    frequency: "Frequency",
    end_date_calculated_automatically: "End date calculated automatically?",
    end_date: "End Date",
    added_on: "Added On",
    start_date: "Start Date",
    share_with_new_user: "Share with new user",
    show_general_info_to_client: "Show General Info To Client?",
    share_strategies: "Share Strategies",
    share: "Share",
    annuity: "Annuity",
    yearly: "Yearly",
    buying_year: "Buying Year",
    end_year: "End Year",
    selling_year: "Selling Year",
    start_year: "Start Year",
    configure_armageddon: "Configure Armageddon",
    change: "Change",
    year: "Year",
    kept_remaining_cash: "Kept remaining cash <b>{amount}</b>",
    saving_cashflow_changes: "Saving cashflow changes",
    maintain_margin: "Maintain margin",
    save: "Save",
    secondary_name: "Secondary Name",
    realtor_seller_name: "Realtor/ seller name + phone number",
    name: "Name",
    sent_remaining_cash:
      "Sent remaining cash <b>{amount}</b> to linked bank account <b>{accountName}</b>",
    welcome_to_ETICA_financials: "Hello! Welcome to Ethica Finance",
    rent: "Rent",
    clone_strategy: "Clone Strategy {strategy}",
    clone: "Clone",
    duplicate: "Duplicate",
    rent_pre_contruction: "Rent Preconstruction",
    rent_post_contruction: "Rent Post Construction",
    total_income_from_rent_minus_monthly_payment:
      "Total income from rent minus total monthly payments",
    total_rent: "Total Rent",
    return_cashflow_monthly: "Expected Monthly Cashflow",
    monthly_rent: "Monthly rent",
    rent_during_contruction:
      "Rent During Construction (default is as pre- demolition)",
    forgot_password: "Forgot password?",
    marginal_rate_of_income: "Marginal rate of income",
    capital_appreciation_tax: "Capital appreciation tax",
    one_off_change: "One Off Change",
    interest_rate_changes: "Interest Rate Changes",
    one_off_change_by: "One off change by",
    heads_up: "Heads Up!",
    update_start_date_note_for_strategies:
      "Please note, This will update the start month and year of each strategy in the customer.",
    area_in_square_meters: "Area In Square Meters",
    unarchive: "Unarchive",
    saving_variable: "Saving Variable",
    saving_admin: "Saving Admin",
    saving_taxbrackets: "Saving Tax Bracket",
    saving_customer: "Saving Customer",
    saving_preset: "Saving Preset",
    archiving_strategy: "Archiving strategy",
    future_value_pre_tax: "Future value pre-tax",
    net_value: "Net value",
    total_value: "Total value",
    value_of_stocks_with_marginal_tax_rate:
      "Value of stocks with marginal tax rate",
    value_of_stocks_with_capital_aprreciation_tax_rate:
      "Value of stocks with capital aprreciation tax rate",
    value_of_apartment_today: "Value of received apartment today",
    value_after_renovation: "Value after renovation",
    appreciation: "Appreciation",
    margin_floor: "Margin Floor",
    level: "Level",
    buying: "Buying",
    mortgage_interest: "Mortgage interest",
    interest: "Interest",
    loan_interest: "Loan Interest",
    profit_from_selling_brfore_tax: "Profit from selling (before tax)",
    profit_from_selling_after_tax: "Profit from selling (after tax)",
    total_net_profit: "Total net profit",
    profit_at_excersising_pre_tax: "Profit at excersising pre tax",
    profit: "Profit",
    pensioni: "Pensioni",
    quaterly: "Quaterly",
    asset_name: "Link Asset",
    link_a_new_liability: "Link a new liability",
    stock_KSH: "stock KSH",
    video_link: "Video Link",
    total_loan_decrease: "Total loan decrease",
    asset_category: "Asset Category",
    category: "Asset Category",
    apartment_floor_number: "Apartment's floor number",
    files_from_drive: "Files From Drive",
    other_files: "Other Files",
    set_a_ceiling_value: "Set a ceiling value",
    set_a_floor_value: "Set a floor value",
    set: "Set",
    get_reset_email: "Get Reset Email",
    fixed: "Fixed",
    view_files: "View Files",
    view_profile: "View Profile",
    yearly_growth_rate: "Yearly Growth Rate (%)",
    balance_sheet_growth_with_time: "Balance Sheet Growth With Time",
    add_new_strategy: "Add New Strategy",
    viewing_user: "Viewing User",
    open_drive_folder: "Open Drive Folder",
    profile_details: "Profile Details",
    difference: "Difference",
    active: "Active",
    actions: "Actions",
    edit_mode: "Edit Mode",
    action: "Action",
    filters: "Filters",
    stock_portfolio: "stock portfolio",
    end_value: "End value",
    monthly_value: "Monthly Value",
    initial_value: "Initial Value",
    value: "Value",
    edit: "Edit",
    yearly_appreciation: "Yearly appreciation",
    annual_appreciation: "Annual Appreciation",
    expected_value_appreciation_from_change:
      "Expected Value Appreciation From Additional Costs",
    expected_appreciation: "Expected Appreciation",
    value_added_by_renovation: "Value Added by Renovation",
    do_we_need_to_pay_material_cost_index:
      "Do we need to pay material cost index?",
    renovation_cost: "Renovation cost",
    total_deal_cost: "Total deal cost",
    cost_of_retailer_lawyer:
      "Cost of realtor, lawyer, buying tax and all related costs",
    realtor_cost_in_percentage_terms_pre_vat:
      "Realtor cost (in percentage terms pre V.A.T)",
    cost_of_time_to_delivery_after_buying:
      "Cost of time to delivery after buying",
    cost_of_vacancy_and_annual_repairs: "Cost of vacancy and annual repairs",
    realtor_cost: "Realtor cost (including VAT)",
    purchase_cost: "Purchase Cost",
    additional_buy_cost: "Additional Buying Cost",
    sales_cost: "Sales Cost",
    additional_sell_cost: "Additional Selling Cost",
    related_costs: "Related costs (lawyer, apraiser etc.)",
    additional_cost: "Additional Cost",
    additional_purchase_cost_for: "Additional Purchase Cost for",
    additional_costs_for_making_the_apartment_ready_for_rent_paper_apartment:
      "Additional costs for making the apartment ready for rent",
    city: "City",
    drive_folder_not_created:
      "A drive folder for this client has not yet been created. Tap here to create one",
    initial_account_balance: "Initial Account Balance",
    update_reinvestment: "Update Reinvestment",
    update_strategy_name: "Update Strategy Name",
    update_cashflow_change: "Update Cashflow Change",
    group_update: "Group Update",
    update_variable: "Update Variable",
    update_admin: "Update Admin",
    update_taxbrackets: "Update Tax Bracket",
    update_customer: "Update Customer",
    resort_to_default: "Resort to default",
    update_notes: "Update Notes",
    reapply_comp: "Reapply Comp",
    update_preset: "Update Preset",
    updating_preset: "Updating Preset",
    update: "Update",
    updating_armageddon_scenario: "Updating Armageddon Scenario",
    update_strategy_start_time: "Update Strategy Start Time",
    updating_cashflow_changes: "Updating cashflow changes",
    to: "To",
    past: "Past",
    symbol: "Symbol",
    old_password: "Old Password",
    new_password: "New Password",
    password: "Password",
    action_summary: "Action Summary",
    loan_summary: "Loan Summary",
    one_off_event_summary: "One Off Event Summary",
    end_with_asset: "End with asset",
    end_with_maturity: "End with maturity",
    end: "End",
    stock_type: "Stock Type",
    program_type: "Program Type",
    type_of_interest: "Interest Type",
    interest_type: "Interest Type",
    transfer_type: "Transfer Type",
    loan_type: "Loan Type",
    apartment_type: "Apartment Type",
    type: "Type",
    total_assets: "Total Assets",
    total_liabilities: "Total Liabilities",
    total_income: "Total Income",
    total_expenditure: "Total Expenditure",
    total: "Total",
    rearrange_strategies: "Rearrange Strategies",
    close: "Close",
    shown_to_customer: "Shown To Customer",
    ignored_assets: "Ignored Assets",
    related_assets: "Related Assets",
    linked_asset: "Linked Asset ",
    assets: "Assets",
    asset_liquidated_on: "Asset liquidated on <b>{date}</b>",
    asset_is_linked_ib_stock:
      "This asset is the linked IB stock of the liability. So trying partial selling",
    asset: "Asset",
    can_sell_partially: "Can Sell Partially?",
    percentage_of_payment_delayed_to_delivery:
      "Percentage of payment delayed to delivery",
    risk_management: "Risk Management",
    manage_users: "Manage Users",
    stocks: "Stocks",
    net_after_excersising_and_selling_stocks:
      "Net after excersising and selling stocks",
    net: "Net",
    real_estate: "Real Estate",
    selected: "Selected",
    advanced: "Advanced",
    new_variables: "New Variables",
    variables: "Variables",
    user_already_invited:
      "This user has already been invited once. Proceeding will update the current user id and password of the user.",
    mortgage_to_be_taken:
      "Mortgage to be taken (this will depend on several options)",
    maximal_mortgage_available: "Maximal Mortgage Available",
    mortgage: "Mortgage",
    is_salary: "Is Salary",
    unarchiving_customer: "Unarchiving customer",
    something_went_wrong_try_again:
      "Something went wrong! Click Here to try again",
    margin_call: "Margin Call",
    showing: "Showing",
    normal_state: "Normal State",
    detailed_mode: "Detailed Mode",
    extreme_case: "Extreme Case",
    depressed_state: "Depressed State",
    mode: "Mode",
    status: "Status",
    updating_strategy_name: "Updating strategy name",
    updating_video_link: "Updating Video Link...",
    updating_variable: "Updating Variable",
    updating_admin: "Updating Admin",
    updating_taxbrackets: "Updating Tax Bracket",
    updating_customer: "Updating Customer",
    updating_notes: "Updating Notes",
    archiving_customer: "Archiving customer",
    vat: "V.A.T",
    total_years: "Total Years",
    number_floor_in_building: "Number of floors in the building",
    user_id: "User Id",
    secondary_phone_number: "Secondary Phone Number",
    phone_number: "Phone Number",
    months_to_sustain_negative:
      "Months to Sustain Negative Cashflow (After Crash)",
    number_of_rooms: "number of rooms",
    buying_tax: "Buying Tax",
    buying_tax_for: "Buying Tax for",
    tax_on_excersising: "Tax on excersising (selling stocks)",
    tax_on_rent: "Tax on rent",
    tax_calculated_automatically: "Tax calculated automatically?",
    buying_tax_calculated_automatically: "Buying Tax calculated automatically?",
    selling_tax_calculated_automatically:
      "Selling Tax calculated automatically?",
    total_tax: "Total Tax",
    tax_amount: "Tax Amount",
    tax_and_additional_costs: "Tax and additional costs",
    selling_tax: "Selling Tax",
    stock: "STOCK",
    admins: "Admins",
    new_admin: "New Admin",
    sorting_by: "Sorting By",
    partially_sold_from_asset:
      "Partially sold <b>{amount}</b> from asset <b>{assetName}</b> to meet the margin requirements.",
    partial_selling_not_possible:
      "Partial Selling is not possible for this stock. Trying complete liquidation",
    selling: "Selling",
    sell: "Sell",
    sort_by: "Sort By",
    fetching_admins: "Fetching admins",
    apartment_info: "Apartment Info",
    additional_information: "Additional Information",
    general_information: "General Info",
    who_is_typical_renter_for_apartment:
      "Who is the typical renter for the apartment?",
    allowed_calculators: "Allowed Calculators",
    calculators: "Calculators",
    pinui_binui: "Pinui Binui",
    irr_calculator: "IRR Calculator",
    target_price_calculator: "Target Price Calculator",
    paper_apartment: "Paper apartment",
    rsu_options: "RSU and Options",
    options_calculator: "Options calculator",
    rsu_calculator: "RSU calculator",
    group_delete_cashflow: "Group delete cashflow",
    group_delete_only_asset: "Group delete only Asset",
    group_delete_liability: "Group delete liability",
    group_delete_reinvestment: "Group delete reinvestment",
    group_delete_linked_liabilities_also:
      "Group delete linked liabilities also",
    delete_only_asset: "Delete only Asset",
    delete_linked_liabilities_also: "Delete linked liabilities also",
    delete: "Delete",
    wanted_price_per_sqm: "Wanted price per SQM",
    buying_price: "Buying Price",
    options_strike_price: "Options strike price",
    current_stock_price: "Current stock price (Publicly traded companies)",
    selling_price: "Selling price",
    price_per_square_meter: "Price per square meter",
    target_price: "Target Price",
    stock_value_at_options_receival_date:
      "Stock value at options receival date (If publicly traded company then 0)",
    do_we_need_to_pay_material_cost_index_paper_calculator:
      "Do we need to pay material cost index?",
    asked_price: "Asked Price",
    inviting_user: "Inviting user",
    cash: "Cash",
    adding_strategy: "Adding strategy",
    deleting_file: "Deleting file",
    deleting_variable: "Deleting Variable",
    deleting_admin: "Deleting admin",
    deleting_taxbrackets: "Deleting Bracket",
    deleting_customer: "Deleting customer",
    deleting_preset: "Deleting Preset",
    deleting_strategy: "Deleting strategy",
    new_tax_bracket: "New Bracket",
    selling_tax_brackets_only_apartment:
      "Selling Tax Brackets [Only Apartment]",
    selling_tax_brackets: "Selling Tax Brackets",
    buying_tax_brackets_only_apartment: "Buying Tax Brackets [Only Apartment]",
    buying_tax_brackets: "Buying Tax Brackets",
    taxbrackets: "Tax Brackets",
    yearly_materials_cost_index_rise_paper_calculator:
      "Yearly materials cost index rise",
    yearly_materials_cost_index_rise_comp: "Yearly materials cost index rise",
    additional_costs_for_making_the_apartment_ready_for_rent:
      "Additional costs for making the apartment ready for rent",
    stress_test: "Stress Test",
    resetting_comp: "Resetting comp",
    balance_sheet: "Balance Sheet",
    from: "From",
    took_from_asset: "Took <b>{amount}</b> from asset <b>{assetName}</b>",
    took_from_linked_bank_account:
      "Took <b>{amount}</b> from linked bank account <b>{accountName}</b>",
    customers: "Customers",
    clone_customer: "Clone Customer",
    new_customer: "New Customer",
    asset_has_linked_loans:
      "The asset you are trying to delete has {n} loans linked to it. Do you also want to delete the loans?",
    asset_has_negative_value:
      "Asset <b>{assetName}</b> has negative value on <b>{date}</b>",
    asset_has_no_money: "Asset <b>{assetName}</b> has no value",
    meeting_video_link: "Meeting Video Link",
    real_estate_guidance: "Real estate guidance",
    press_alt_to_move:
      "Press alt on Windows or option on Mac to move the chart around",
    logs: "Logs",
    no_stocks_with_linked_liabilities:
      "No stocks with linked liabilities found!",
    could_not_use_asset_loan_is_greater:
      "Could not use this asset, Loan is greater than liquidated value of this asset. Liquidated Value: <b>{liquidationAmount}</b>, LOAN Value: <b>{loanAmount}</b>",
    no_strategies_created: "No strategies created",
    no_notes_added: "No notes added",
    no: "No",
    address: "Address",
    cushions: "Cushions",
    available_level1_funds_before_crash:
      "Available Level1 Funds (Before Crash)",
    available_level1_funds_after_crash: "Available Level1 Funds (After Crash)",
    yes: "Yes",
    stock_amount: "Stock amount",
    options_to_cash_after_two_years:
      "Options to cash (after two years of holding)",
    options_to_cash_pre_two_years: "Options to cash (Pre two years of holding)",
    setup_mode: "Setup Mode",
    already_have_an_account: "Already have an account? Click here to login",
    remaining_payment: "Remaining Payment",
    mortgage_left_at_the_end: "Mortgage left at the end of period of holding",
    one_final_payment: "One Final Payment",
    not_enough_assets:
      "Remaining amount is <b>{amount}</b>. Not enough assets to liquidate",
    some_investment_are_not_applied:
      "Some of the investments might not have been applied because this strategy has cyclic investments. Please correct them below",
    assets_decrease: "Assets Decrease",
    value_lost_in_months: "Value lost in 6 months",
    depreciations: "Depreciations",
    maximal_drawdown: "Maximal Drawdown",
    target: "Target",
    creating_an_account: "Creating an account for {email}",
    upload_files_to_this_apartment: "Upload Files To This Apartment",
    loading_file: "Loading file",
    fetching_customers: "Fetching Customers",
    liquidation_table: "Liquidation Table",
    opening_balance: "Opening Balance",
    linked_bank_account: "Linked Bank Account",
    primary_bank_account: "Primary Bank Account",
    semi_yearly: "Semi Yearly",
    asset_class_distribution: "Asset Class Distribution",
    quick_search: "Quick Search...",
    search: "Search",
    back_to_site: "Back to site",
    monthly: "Monthly",
    buying_month: "Buying Month",
    end_month: "End Month",
    selling_month: "Selling Month",
    start_month: "Start Month",
    starting_month: "Starting Month",
    month: "Month",
    new: "New",
    estimated_time_for_finishing_contruction:
      "Estimated time for finishing construction from demolition in years",
    estimated_time_for_contruction:
      "Estimated time for finishing construction in years",
    estimated_time_for_contruction_months:
      "Estimated time for finishing construction in months",
    estimated_time_for_demolition: "Estimated time for demolition in years",
    mortgage_time_to_maturity: "Mortgage time to maturity",
    time_to_maturity: "Time To Maturity (Months)",
    time_to_delivery_after_buying: "Time to delivery after buying (months)",
    holding_period_in_years: "Holding period in years",
    this_will_also_delete_related_investments:
      "This will also delete their related investments (if any).",
    app_videos: "App Videos",
    video_not_found_please_contact_admin:
      "Video not found, Please contact the admin of the site",
    logout: "Logout",
    start: "Start",
    liability_ends_with: "Liability Ends With",
    duplicate_linked_liabilities:
      "This asset also has liabilities linked to it. Do you also want to duplicate them?",
    liabilities: "Liabilities",
    sign_in_to_continue: "Sign in to continue",
    login: "Login",
    reinvestments: "Reinvestments",
    cashflow_impacts: "Cashflow Impacts",
    compare_strategies: "Compare Strategies",
    strategies_comparison: "Strategies Comparison",
    leave_empty_to_view_results: "Leave empty to view recent results...",
    show_stress_test_to_client: "Show Stress Test to Client?",
    show_all_strategies_from_customer: "Show all strategies to customer",
    show_archived_to_client: "Show Archived to Client?",
    show: "Show",
    meeting_video: "Meeting Video",
    still_insufficient_amount_for_buying:
      "Materials cost indexing to be paid at construction end",
    show_explainatory_video: "Show Explainatory Video",
    show_archived: "Show Archived",
    difference_between_value_and_price:
      "Difference between appraised value and asked price",
    apply_stress_test: "Apply Stress Test",
    additional_comments: "Additional comments",
    notes: "Notes",
    upload: "Upload",
    upload_files: "Upload Files",
    reinvestment_and_gradual_selling: "Reinvestment and Gradual Selling ",
    transactions: "Transactions",
    archive: "Archive",
    hide_zero_rows: "Hide rows with 0 cashflow",
    hide_explainatory_video: "Hide Explainatory Video",
    hide_all_strategies_from_customer: "Hide all strategies from customer",
    hide: "Hide",
    negative_amount_is: "Negative amount is <b>{amount}</b>",
    remaining_amount_trying_asset:
      "Remaining amount is <b>{amount}</b>. Trying asset <b>{assetName}</b>",
    required_amount_for_margin_is:
      "Required amount for margin requirements is <b>{amount}</b>",
    asset_liquidated_from_to:
      "Asset liquidated from <b>{date1}</b> to <b>{date2}</b>",
    asset_linked_asset_of_loan:
      "Current asset is linked asset of the loan. Needs to be liquidated. Liquidated Value: <b>{liquidatedValue}</b>. Remaining Loan Amount: <b>{loanValue}</b>",
    comp_table: "Comp Table",
    user_has_not_signed_up_yet: "User has not signed up yet",
    continue: "Continue",
    convert_from_another_currency: "Convert from another currency",
    convert: "Convert",
    customer_shared: "This customer has been shared with the following users.",
    customer_not_shared:
      "This customer has not been shared with other users yet!",
    margin_loan_against: "Margin Loan Against",
    fixed_income: "Fixed Income",
    loan_to_asset: "Loan To Asset",
    loan_against: "Loan Against",
    loan: "LOAN",
    total_income_from_rent_after_vacancy_and_tax:
      "Total income from rent (after vacancy and tax)",
    total_income_from_rent: "Total income from rent",
    income: "Income",
    enter_otp_here: "Enter OTP Here",
    all: "All",
    holding_postponing_tax: "Holding and postponing the tax",
    register: "Register",
    subtract: "Subtract",
    transfer_applied_to: "Transfer Applied To",
    apply: "Apply",
    reapply: "Reapply",
    total_monthly_payments: "Total monthly mortgage payments",
    monthly_mortgage_payment: "Maximal Monthly mortgage payment",
    invite_user: "Invite User",
    the_weakest_month_and_year:
      "The weakest month and year of this strategy is",
    invite: "Invite",
    cleared_linked_loan: "Cleared linked loan of value: <b>{clearedLoan}</b>.",
    cleared_linked_loan_remaining_cash:
      "Cleared linked loan of value: <b>{clearedLoan}</b>. Remaining cash: <b>{remainingCash}</b>",
    download: "Download",
    expenditure: "Expenditure",
    add_cashflow: "Add Cashflow",
    update_cashflow: "Update Cashflow",
    add_new_change: "Add new change",
    add_new_cashflow_change: "Add Cashflow Change",
    group_add: "Group Add",
    add_value: "Add value",
    add_new_asset: "Add New Asset",
    add_asset: "Add Asset",
    add_apartment: "Add Appartment",
    add_new_variable: "Add New Variable",
    add_new_admin: "Add New Admin",
    add_new_taxbrackets: "Add New Tax Bracket",
    add_new_customer: "Add New Customer",
    add_new: "Add New",
    add_liability: "Add Liability",
    add_reinvestment: "Add Reinvestment",
    add_new_preset: "Add New Preset",
    add: "Add",
    equity_received: "Equity Received",
    total_equity_for_buying: "Total equity for buying",
    equity_for_taking_mortgage: "Equity for taking mortgage",
    equity_to_assets: "Equity To Assets",
    total_equity_to_put_in_the_deal: "Total equity to put in the deal",
    equity: "Equity",
    equity_for: "Equity for",
    required_equity_for_excercising: "Required equity for excercising (strike)",
    app_configuration: "App Configuration",
    preset: "Preset",
    strategies_archived: "The following strategies were archived!",
    is_rent: "Is Rent?",
    is_there_an_balcony: "Is there a balcony?",
    is_there_an_elevator: "Is there an elevator?",
    is_there_a_safe_room: "Is there a safe room?",
    is_there_parking: "Is there parking? Is it legaly registered?",
    is_there_garden: "Is there a garden?",
    is_only_apartment: "Is Only apartment",
    is_it_the_only_apartment_buying: "Is it the only apartment when buying",
    is_it_the_only_apartment_selling: "Is it the only apartment when selling",
    is_apartment_properly_registered: "Is the apartment properly registered?",
    is_there_construction_without_permit:
      "is there any construction without permit?",
    is_apartment_registered_on_seller_name:
      "Is the apartment registered on the seller's name?",
    is_apartment_abroad: "Is Apartment Abroad?",
    are_you_sure_you_want_to_archive_strategy:
      "Are you sure you want to archive this strategy ({strategy})?",
    are_you_sure_you_want_to_unarchive_strategy:
      "Are you sure you want to unarchive this strategy ({strategy})?",
    are_you_sure_you_want_to_unselect_strategy:
      "Are you sure you want to unselect this strategy ({strategy})?",
    are_you_sure_you_want_to_select_strategy:
      "Are you sure you want to select this strategy ({strategy})?",
    liquidation_score: "Liquidation Score",
    rate_from_1_to_10: "Rate from 1 to 10 (1- Terrible 10- Excellent)",
    how_easy_to_find_renters:
      "How easy is it to find renters for the apartment?",
    how_well_maintained: "How well maintained is the apartment?",
    how_good_is_location: "How good is the location?",
    how_good_are_current_renters: "How good are the current renters?",
    linked_apartment: "Linked Apartment",
    apartment: "Apartment",
    tenant_stops_paying: "Tenant stops paying",
    charts: "Charts",
    interest_only: "Interest only",
    cashflow_appreciation: "Cashflow Appreciation",
    loan_provider: "Loan Provider",
    apartment_size: "apartment's size",
    apartment_size_after_reconstruction: "Apartment size after reconstruction",
    loan_value: "Loan Value",
    new_presets: "New Presets",
    presets: "Presets",
    highest_earner: "Highest Earner",
    balance_with: "Balance With",
    weakest: "Weakest",
    yearly_materials_cost_index_rise: "Yearly materials cost index rise",
    balloon: "Balloon",
    home: "Home",
    unarchiving_strategy: "Unarchiving strategy",
    unselecting_strategy: "Unselecting strategy",
    disable_reinvestment: "Disable all reinvestments",
    unselect: "Unselect",
    are_you_sure_you_want_to_delete_taxbrackets:
      "Are you sure you want to delete this Bracket? This action cannot be undone",
    linked_bank_account_has_no_money:
      "Linked bank account <b>{accountName}</b> has no money",
    select_unselect_all: "Select/Unselect All",
    select: "Select",
    selecting_strategy: "Selecting strategy",
    please_provide_a_primary_bank_account:
      "Please provide a primary bank account for this strategy",
    are_you_sure_you_want_to_unarchive_customer:
      "Are you sure you want to unarchive the customer ({userName}) ? This action cannot be undone",
    are_you_sure_you_want_to_delete_cashflow:
      "Are you sure you want to delete this Cashflow? This action cannot be undone",
    are_you_sure_you_want_to_delete_asset:
      "Are you sure you want to delete this Asset? This action cannot be undone",
    are_you_sure_you_want_to_delete_liability:
      "Are you sure you want to delete this Liability? This action cannot be undone",
    are_you_sure_you_want_to_delete_investment:
      "Are you sure you want to delete this investment option? This action cannot be undone",
    are_you_sure_you_want_to_delete_one_off_event:
      "Are you sure you want to delete this One Off Event? This action cannot be undone",
    are_you_sure_you_want_to_archive_customer:
      "Are you sure you want to archive the customer ({userName}) ? This action cannot be undone",
    are_you_sure_you_want_to_reapply:
      "Are you sure to reapply the comp table to this strategy? We recommend you make a clone of the original strategy first",
    are_you_sure_you_want_to_delete_admin:
      "Are you sure you want to delete this Admin ({admin})? This action cannot be undone",
    are_you_sure_you_want_to_delete_customer:
      "Are you sure you want to delete the customer ({userName}) ? This action cannot be undone",
    are_you_sure_delete_file:
      "Are you sure to delete this file ({fileName}). You will lose access to this file permanently?",
    are_you_sure_you_want_to_delete_variable:
      "Are you sure you want to delete this Variable? This action cannot be undone",
    are_you_sure_you_want_to_delete_preset:
      "Are you sure you want to delete this Preset? This action cannot be undone",
    are_you_sure_you_want_to_delete_strategy:
      "Are you sure you want to delete this Strategy ({strategy})? This action cannot be undone",
    are_you_sure_reset_comp_table:
      "Are you sure you want to reset the Comp Table to default? This action cannot be undone!",
    confirm_password: "Confirm Password",
    strategy_archive: "Strategy ARCHIVE",
    archived: "Archived",
    reset_to_default: "Reset To Default",
    strategies: "Strategies",
    new_strategy: "New Strategy",
    strategy: "Strategy",
    anona: "Anona",
    please_provide_a_primary_bank_account_for_this_strategy:
      "Please provide a primary bank account for this strategy",
    please_provide_your_email_address:
      "Please provide your email address to continue",
    alphabetically: "Alphabetically",
    real_estate_full_service: "Real estate full service",
    reset_zoom: "Reset Zoom",
    no_name: "No name",
    no_files_to_show: "No files to show!",
    no_asset: "No Asset",
    margin_not_met:
      "Margin for {stockType} loan <b>{loanName}</b> has not been met on <b>{date}</b>",
    nothing_to_show: "Nothing to show!",
    dont_have_an_account: "Don't have an account? Click here to register",
    no_incomes: "No Incomes",
    no_expenditure: "No Expenditures",
    no_email: "No email",
    recipient_emails: "Recipient Emails",
    secondary_email: "Secondary Email",
    email: "Email",
    other: "Other",
    mortgage_percentage: "Mortgage percentage",
    percentage: "Percentage",
    problems_detected: "Problems Detected",
    appraised_value: "Appraised Value",
    crash_percentage: "Crash Percentage",
    loses_place_of_work: "Loses a place of work",
    showing_n_items: "{n} items",
    please_wait_n_secs:
      "Please wait {timer} seconds before requesting a new OTP...",
    did_not_receive_send_otp_again:
      "Didn't receive OTP? Click here to send again...",
    logging_in: "Logging In",
    checking_email: "Checking email",
    creating_account: "Creating account",
    please_wait: "Please wait...",
    value_in_currency: "Value in {currency}",
    hello: "Hello!",
    welcome_to_ETICA_crm: "Welcome to Ethica CRM",
    please_reset_your_password: "Please create a password",
    contacts: "Contacts",
    how_to_use_app: "How to use App?",
    comments: "Comments",
    contracts: "Contracts",
    inbounds: "Inbounds",
    emails: "Emails",
    phone_calls: "Phone Calls",
    no_comments_to_show: "No comments to show!",
    no_contracts_to_show: "No contracts to show!",
    type_your_comment_here: "Type your comment here...",
    reset: "Reset",
    are_you_sure_delete_comment:
      "Are you sure you want to delete this comment? This action cannot be undone",
    admin: "Admin",
    products: "Products",
    add_new_product: "Add New Product",
    update_product: "Update Product",
    price: "Price",
    template_link: "Template Link on Prospero",
    are_you_sure_you_want_to_delete_products:
      "Are you sure you want to delete the product ({productName}) ? This action cannot be undone",
    send_new_contract: "Send New Contract",
    edit_and_send_contract: "Edit & Send",
    send: "Send",
    quote: "Quote",
    anona_monthly_payment: "Anona Monthly Payment",
    source: "Source",
    quote: "Quote",
    followup_date: "Follow Up Date",
    details: "Details",
    inbound_source_details: "Inbound Source Details",
    events: "Events",
    users: "Users",
    cancel: "Cancel",
    add_new_event: "Add Event",
    update_event: "Update Event",
    event_date: "Event Date",
    facebook_campaign: "Facebook Campaign",
    select_campaign: "Select Campaign",
    active_trail_list: "Active Trail List",
    select_trail_list: "Select Trail List",
    add_new_user: "Add User",
    update_user: "Update User",
    are_you_sure_you_want_to_delete_events:
      "Are you want to delete this event? This action cannot be undone",
    are_you_sure_you_want_to_delete_user:
      "Are you certain you wish to delete this user? Deleting this user may impact contacts, so kindly assign another user in replace or remove them from all contacts.",
    are_you_sure_you_want_to_delete_tag:
      "Are you certain you wish to delete this tag? Deleting this tag may impact contacts, so kindly assign another tag in replace or remove them from all contacts.",
    websites: "Websites",
    previous_unsaved_contact:
      "The contact {name} has unsaved changes. Do you want to save the changes before proceeding?",
    call: "Call",
    whatsapp: "Whatsapp",
    set_appointment: "Set Appointment",
    add_new_contact: "Add New Contact",
    first_name: "First Name",
    last_name: "Last Name",
    spouse_first_name: "Spouse First Name",
    spouse_last_name: "Spouse Last Name",
    referrer: "Referrer",
    adding_new_row: "Adding New Row",
    change_logs: "Change Logs",
    made_the_following_change_on: "made the following changes on",
    added: "Added",
    updated: "Updated",
    removed: "Removed",
    salesperson: "Salesperson",
    add_appointment: "Add Appointment",
    update_appointment: "Update Appointment",
    participants: "Participants",
    automationAndevents: "Automation & Events",
    appConfig: "App Configuration",
    appointment_defaults: "Appointment Defaults",
    update_appointment_default_type: "Update Appointment Default Type",
    title: "Title",
    automations: "Automation",
    are_you_sure_you_want_to_delete_automation:
      "Are you want to delete this automation? This action cannot be undone",
    add_new_automation: "Add new automation",
    update_automation: "Update automation",
    duration: "Duration",
    new: "New",
    phone_call_unanswered: "Phone Call Unanswered",
    webinar: "Webinar",
    sales: "Sales",
    expressed_interest: "Expressed Interest",
    finished_first_phone_call: "Finished First Phone Call",
    was_in_meeting: "Was in Meeting",
    contract_sent: "Contract Sent",
    contract_signed: "Contract Signed",
    doesnt_meet_our_requirements: `Doesn’t Meet Our Requirements`,
    meeting_scheduled:'Meeting Scheduled',
    didnt_answer_5_times: `Didn’t Answer 5 Times`,
    asked_to_not_be_contacted: "Asked To Not be Contacted",
    not_interested_now: "Not Interested Now",
    client_paid: "Client Paid",
    clients: "Clients",
    client_in_process: "Client in Process",
    client_finished: "Client Finished",
    awaiting_upsale: "Awaiting Upsale",
    on_hold: "On Hold",
    please_select_one: "Please Select One",
    inbound_source_default_status: "Inbound Source Default Status",
    update_default_status: "Update Default Status",
    inboundSource: "Inbound Source",
    exceptions: "Exceptions",
    add_exceptions: "Add Exceptions",
    irrelevant: "Irrelevant",
    confirm_password: "Confirm Password",
    submit: "Submit",
    already_have_an_account: "Already have an account? Click here to login",
    ethica_finance: "Ethica Finance",
    no_any_logs: "No any logs available",
    send_to_rujum: "Send to Rujum",
    get_reset_email: "Get Reset Email",
    update_user_permissions: "Update User Permissions",
    rule: "Rule",
    go_to_rujum: "Go to Rujum",
    tags: "Tags",
    update_tag: "Update Tag",
    add_tag: "Add Tag",
    are_you_sure_you_want_to_delete_contacts:
      "Are you sure you want to delete selected contacts?",
    filter: "Filter",
    edit_multiple_row: "Edit multiple Row",
    any: "Any",
    are_you_sure_you_want_to_delete_filter:
      "Are you sure you want to delete this filter",
    saved_filters: "Saved Filters",
    custom_filters: "Custom Filters",
    enter_name: "Enter Name",
    save_and_apply: "Save & Apply",
    manually_added: "Manually Added",
    follow_up_date: "Follow Up Date",
    sales_person: "Sales Person",
    financial_strategist: "Financial Strategist",
    real_estate_analyst: "Real Estate Analysist",
    phone_numbers: "Phone Numbers",
    emails: "Emails",
    last_inbound_date: "Last Inbound Date",
    last_inbound_source_campaign_url: "Last Inbound Source (Campaign/Url)",
    last_inbound_source_type: "Last Inbound Source (Type)",
    contains: "Contains",
    begins_with: "Begins With",
    ends_with: "Ends With",
    does_not_contain: "Does not contain",
    does_not_begin_with: "Does not begin with",
    does_not_end_with: "Does not end with",
    is_null: "Is null",
    is_not_null: "Is not null",
    in: "In",
    not_in: "Not In",
    between: "Between",
    not_between: "Not Between",
    deals: "Deals",
    contract_sent_on: "Contract sent on",
    deal_value: "Deal Value",
    sent_by: "Sent By",
    // client: "Client",
    published: "Published",
    signed: "Signed",
    opened: "Opened",
    declined: "Declined",
    no_payments_to_show: "No payments to show",
    add_payment: "Add Payment",
    update_payment: "Update Payment",
    amount: "Amount",
    date: "Date",
    invoice_link: "Invoice Link",
    payment_details: "Payment Details",
    payment_received: "Payment Received",
    are_you_sure_you_want_to_delete_payment:
      "Are you sure you want to delete this payment?",
    editing_filter: "Editing ({filterName})",
    show_events_of: "Show Events Of:",
    custom_filter: "Custom filter",
    updating_filter: "Updating filter...",
    today: "Today",
    prev_day: "Previous Day",
    prev_month: "Previous Month",
    prev_week: "Previous Week",
    next_day: "Next Day",
    next_week: "Next Week",
    next_month: "Next Month",
    export_as_csv: "Export as CSV",
    cancel: "Cancel",
    clear_filters: "Clear Filters",
    nothing_added:'Nothing Added!'
  },
 
};

export const languageOptions = Object.keys(languageContent);

export const getActiveLanguage = () => {
  return localStorage.getItem("language") || "English";
};

export const setActiveLanguage = (lang = "English") => {
  return localStorage.setItem("language", lang);
};

export const isRtl = (language) => {
  return language === "Hebrew";
};
